import { HIGH_STAR_CATALOG_SKILLS } from "./catalogHighStar.js";
import type { CatalogSkill } from "./types.js";

export const CATALOG_SKILLS: CatalogSkill[] = [
  {
    id: "nature-writing",
    name: "nature-writing",
    title: "Nature 论文写作",
    description: "面向 Nature/CNS 风格的科研论文结构、表达和段落写作。",
    source: "https://github.com/Yuan1z0825/nature-skills/tree/main/skills/nature-writing",
    repository: "https://github.com/Yuan1z0825/nature-skills",
    category: "学术写作",
    tags: ["nature", "academic", "writing"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合你提到的专业写作场景，可通过提示显式调用。",
    examplePrompt: "使用 nature-writing skill，帮我把这段 Results 改成 Nature 风格。"
  },
  {
    id: "nature-polishing",
    name: "nature-polishing",
    title: "Nature 学术润色",
    description: "Nature 风格英文润色、重写和中英文学术表达优化。",
    source: "https://github.com/Yuan1z0825/nature-skills/tree/main/skills/nature-polishing",
    repository: "https://github.com/Yuan1z0825/nature-skills",
    category: "学术写作",
    tags: ["nature", "polishing", "academic"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合论文语言提升和专业表达打磨。",
    examplePrompt: "调用 nature-polishing，把下面的 Introduction 润色到 Nature 子刊语气。"
  },
  {
    id: "nature-citation",
    name: "nature-citation",
    title: "Nature 引文与参考文献",
    description: "严格检索 Nature/CNS 家族引用，支持 ENW、RIS、Zotero RDF 等导出场景。",
    source: "https://github.com/Yuan1z0825/nature-skills/tree/main/skills/nature-citation",
    repository: "https://github.com/Yuan1z0825/nature-skills",
    category: "学术写作",
    tags: ["nature", "citation", "reference"],
    agents: ["codex", "claude-code"],
    featuredReason: "补齐论文写作中的引用管理能力。",
    examplePrompt: "使用 nature-citation，为这段论述找 5 篇 Nature/CNS 相关引用。"
  },
  {
    id: "nature-figure",
    name: "nature-figure",
    title: "Nature 科研绘图",
    description: "生成符合 Nature 期刊风格的 matplotlib/ggplot2 科研图。",
    source: "https://github.com/Yuan1z0825/nature-skills/tree/main/skills/nature-figure",
    repository: "https://github.com/Yuan1z0825/nature-skills",
    category: "科研图表",
    tags: ["nature", "figure", "plot"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合论文图表规范化和投稿前美化。",
    examplePrompt: "调用 nature-figure，把这个 CSV 画成 Nature 风格柱状图。"
  },
  {
    id: "nature-response",
    name: "nature-response",
    title: "审稿回复",
    description: "撰写逐点审稿回复，处理 reviewer comment、修改映射和风险检查。",
    source: "https://github.com/Yuan1z0825/nature-skills/tree/main/skills/nature-response",
    repository: "https://github.com/Yuan1z0825/nature-skills",
    category: "学术写作",
    tags: ["nature", "reviewer", "response"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合返修阶段的 rebuttal 和 response letter。",
    examplePrompt: "使用 nature-response，帮我整理这批 reviewer comments 的逐点回复。"
  },
  {
    id: "vercel-react-best-practices",
    name: "vercel-react-best-practices",
    title: "React/Next 最佳实践",
    description: "Vercel 官方 React 与 Next.js 性能优化规则集合。",
    source: "https://github.com/vercel-labs/agent-skills/tree/main/skills/react-best-practices",
    repository: "https://github.com/vercel-labs/agent-skills",
    category: "前端工程",
    tags: ["react", "nextjs", "performance"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合前端项目 review、性能优化和代码生成约束。",
    examplePrompt: "调用 react-best-practices，审查这个 Next.js 页面性能问题。"
  },
  {
    id: "vercel-web-design-guidelines",
    name: "web-design-guidelines",
    title: "Web 设计规范",
    description: "Vercel agent skills 中的 Web 设计指导，用于更稳定地产出页面设计。",
    source: "https://github.com/vercel-labs/agent-skills/tree/main/skills/web-design-guidelines",
    repository: "https://github.com/vercel-labs/agent-skills",
    category: "前端设计",
    tags: ["web", "design", "ui"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合提升 UI 生成质量，减少模板感。",
    examplePrompt: "使用 web-design-guidelines，重新设计这个后台页面。"
  },
  {
    id: "anthropic-template-skill",
    name: "template-skill",
    title: "官方 Skill 模板",
    description: "Anthropic 官方公开仓库中的基础 skill 模板。",
    source: "https://github.com/anthropics/skills/tree/main/template",
    repository: "https://github.com/anthropics/skills",
    category: "Skill 开发",
    tags: ["template", "official", "authoring"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合创建自己的团队 skill 时参考结构。",
    examplePrompt: "使用 template-skill，帮我为团队代码规范创建一个新 skill。"
  },
  {
    id: "eigent-skill-creator",
    name: "skill-creator",
    title: "Skill 创建与评估",
    description: "Eigent 开源集合中的 skill 创建、评估和基准测试工作流。",
    source: "https://github.com/eigent-ai/agent-skills/tree/main/skills/coding-agents-and-ides/skill-creator",
    repository: "https://github.com/eigent-ai/agent-skills",
    category: "Skill 开发",
    tags: ["skill", "authoring", "evaluation"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合把团队经验沉淀成可复用 skill。",
    examplePrompt: "调用 skill-creator，帮我把这份 SOP 改造成 agent skill。"
  },
  {
    id: "jwynia-research-workflow",
    name: "research-workflow",
    title: "研究工作流",
    description: "Jwynia agent-skills 集合中的结构化研究方法 skill。",
    source: "https://github.com/jwynia/agent-skills/tree/main/skills/general/research/methodology/research-workflow",
    repository: "https://github.com/jwynia/agent-skills",
    category: "研究",
    tags: ["research", "workflow", "source"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合资料收集、证据梳理和研究计划。",
    examplePrompt: "使用 research-workflow，帮我设计这个课题的文献调研路径。"
  },
  {
    id: "anthropic-frontend-design",
    name: "frontend-design",
    title: "Anthropic 前端设计",
    description: "Anthropic 官方高星 skills 仓库中的前端设计 skill，用于生成更有质感的网页和组件。",
    source: "https://github.com/anthropics/skills/tree/main/skills/frontend-design",
    repository: "https://github.com/anthropics/skills",
    category: "前端设计",
    tags: ["anthropic", "frontend", "design"],
    agents: ["codex", "claude-code"],
    featuredReason: "Anthropic 官方 skills 仓库约 142k stars，适合放入默认高质量设计工具箱。",
    examplePrompt: "使用 frontend-design skill，帮我把这个管理台页面做一次视觉升级。"
  },
  {
    id: "anthropic-mcp-builder",
    name: "mcp-builder",
    title: "Anthropic MCP 构建",
    description: "Anthropic 官方 MCP server 构建 skill，指导设计高质量 MCP 工具接口。",
    source: "https://github.com/anthropics/skills/tree/main/skills/mcp-builder",
    repository: "https://github.com/anthropics/skills",
    category: "MCP 开发",
    tags: ["anthropic", "mcp", "tooling"],
    agents: ["codex", "claude-code"],
    featuredReason: "来自 Anthropic 官方高星 skills 仓库，适合扩展 agent 外部工具能力。",
    examplePrompt: "调用 mcp-builder，帮我为 GitHub Issues 设计一个 MCP server。"
  },
  {
    id: "anthropic-webapp-testing",
    name: "webapp-testing",
    title: "Anthropic Web 应用测试",
    description: "Anthropic 官方 Web 应用测试 skill，用 Playwright 验证本地网页和交互。",
    source: "https://github.com/anthropics/skills/tree/main/skills/webapp-testing",
    repository: "https://github.com/anthropics/skills",
    category: "测试验证",
    tags: ["anthropic", "playwright", "testing"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合任何需要真实浏览器验证的前端或全栈项目。",
    examplePrompt: "使用 webapp-testing skill，打开 localhost 并检查控制台错误。"
  },
  {
    id: "anthropic-doc-coauthoring",
    name: "doc-coauthoring",
    title: "Anthropic 文档共创",
    description: "Anthropic 官方文档共创 skill，用于结构化写作、提案、技术方案和决策文档。",
    source: "https://github.com/anthropics/skills/tree/main/skills/doc-coauthoring",
    repository: "https://github.com/anthropics/skills",
    category: "文档写作",
    tags: ["anthropic", "docs", "writing"],
    agents: ["codex", "claude-code"],
    featuredReason: "来自 Anthropic 官方高星仓库，适合团队沉淀技术文档与规范。",
    examplePrompt: "调用 doc-coauthoring，帮我把这些要点整理成一份技术方案。"
  },
  {
    id: "vercel-deploy-to-vercel",
    name: "deploy-to-vercel",
    title: "Vercel 一键部署",
    description: "Vercel 官方 agent-skills 中的部署 skill，帮助识别框架并部署 Web 项目。",
    source: "https://github.com/vercel-labs/agent-skills/tree/main/skills/deploy-to-vercel",
    repository: "https://github.com/vercel-labs/agent-skills",
    category: "部署发布",
    tags: ["vercel", "deploy", "web"],
    agents: ["codex", "claude-code"],
    featuredReason: "Vercel 官方 agent-skills 仓库约 27k stars，适合 Web 项目发布流程。",
    examplePrompt: "使用 deploy-to-vercel skill，帮我部署当前前端项目并返回预览链接。"
  },
  {
    id: "vercel-optimize",
    name: "vercel-optimize",
    title: "Vercel 性能与成本优化",
    description: "审计 Vercel 项目的性能、缓存、函数使用、构建分钟和成本优化机会。",
    source: "https://github.com/vercel-labs/agent-skills/tree/main/skills/vercel-optimize",
    repository: "https://github.com/vercel-labs/agent-skills",
    category: "性能优化",
    tags: ["vercel", "performance", "cost"],
    agents: ["codex", "claude-code"],
    featuredReason: "来自 Vercel 官方高星 skills 仓库，适合上线后优化。",
    examplePrompt: "调用 vercel-optimize，检查这个 Vercel 项目的性能和成本问题。"
  },
  {
    id: "vercel-composition-patterns",
    name: "composition-patterns",
    title: "React 组合模式",
    description: "Vercel 官方 React 组件组合模式 skill，用于更稳健的组件 API 和架构。",
    source: "https://github.com/vercel-labs/agent-skills/tree/main/skills/composition-patterns",
    repository: "https://github.com/vercel-labs/agent-skills",
    category: "前端工程",
    tags: ["vercel", "react", "architecture"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合复杂前端组件库、设计系统和可维护性重构。",
    examplePrompt: "使用 composition-patterns，帮我重构这个 React 组件 API。"
  },
  {
    id: "vercel-react-native-skills",
    name: "react-native-skills",
    title: "React Native 技能",
    description: "Vercel 官方 React Native skill，面向移动端项目开发和问题排查。",
    source: "https://github.com/vercel-labs/agent-skills/tree/main/skills/react-native-skills",
    repository: "https://github.com/vercel-labs/agent-skills",
    category: "移动开发",
    tags: ["react-native", "mobile", "vercel"],
    agents: ["codex", "claude-code"],
    featuredReason: "补齐 Web 之外的移动端开发 skill。",
    examplePrompt: "调用 react-native-skills，帮我排查这个 React Native 页面卡顿问题。"
  },
  {
    id: "vercel-react-view-transitions",
    name: "react-view-transitions",
    title: "React View Transitions",
    description: "Vercel 官方 React 视图过渡 skill，用于页面和组件切换动效。",
    source: "https://github.com/vercel-labs/agent-skills/tree/main/skills/react-view-transitions",
    repository: "https://github.com/vercel-labs/agent-skills",
    category: "前端体验",
    tags: ["react", "animation", "view-transition"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合提升产品交互质感，和现有前端设计 skill 互补。",
    examplePrompt: "使用 react-view-transitions，为这个列表详情切换加自然过渡。"
  },
  {
    id: "vercel-writing-guidelines",
    name: "writing-guidelines",
    title: "Vercel 写作规范",
    description: "Vercel 官方写作规范 skill，用于产品文案、技术说明和界面文字。",
    source: "https://github.com/vercel-labs/agent-skills/tree/main/skills/writing-guidelines",
    repository: "https://github.com/vercel-labs/agent-skills",
    category: "文案写作",
    tags: ["writing", "copy", "vercel"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合为产品 UI、README 和技术说明统一文案风格。",
    examplePrompt: "调用 writing-guidelines，帮我改写这个设置页的按钮和提示文案。"
  },
  {
    id: "vercel-find-skills",
    name: "find-skills",
    title: "Vercel Skill 发现",
    description: "Vercel `skills` 工具仓库中的发现 skill，用于根据任务寻找合适的 agent skill。",
    source: "https://github.com/vercel-labs/skills/tree/main/skills/find-skills",
    repository: "https://github.com/vercel-labs/skills",
    category: "Skill 发现",
    tags: ["vercel", "discovery", "skills"],
    agents: ["codex", "claude-code"],
    featuredReason: "Vercel `skills` 工具仓库约 20k stars，适合帮助用户寻找更多可安装 skill。",
    examplePrompt: "使用 find-skills，帮我找适合数据库迁移审查的 skill。"
  },
  {
    id: "microsoft-docs",
    name: "microsoft-docs",
    title: "Microsoft Docs 检索",
    description: "Microsoft 官方 skills 仓库中的文档检索 skill，用于从 Microsoft Learn 获取权威上下文。",
    source: "https://github.com/microsoft/skills/tree/main/.github/skills/microsoft-docs",
    repository: "https://github.com/microsoft/skills",
    category: "微软生态",
    tags: ["microsoft", "docs", "azure"],
    agents: ["codex", "claude-code"],
    featuredReason: "Microsoft 官方 skills 仓库，适合 Azure、Foundry、SDK 等文档驱动开发。",
    examplePrompt: "调用 microsoft-docs，查找 Azure AI Search 最新的索引配置文档。"
  },
  {
    id: "microsoft-kql",
    name: "kql",
    title: "Microsoft KQL",
    description: "Microsoft 官方 KQL skill，用于编写、解释和优化 Kusto Query Language 查询。",
    source: "https://github.com/microsoft/skills/tree/main/.github/skills/kql",
    repository: "https://github.com/microsoft/skills",
    category: "数据分析",
    tags: ["microsoft", "kql", "azure"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合日志分析、Application Insights、Azure Monitor 等场景。",
    examplePrompt: "使用 kql skill，帮我写一个查询最近 24 小时错误率的 KQL。"
  },
  {
    id: "microsoft-cloud-solution-architect",
    name: "cloud-solution-architect",
    title: "Microsoft 云方案架构",
    description: "Microsoft 官方云方案架构 skill，用于 Azure 架构设计和方案评审。",
    source: "https://github.com/microsoft/skills/tree/main/.github/skills/cloud-solution-architect",
    repository: "https://github.com/microsoft/skills",
    category: "云架构",
    tags: ["microsoft", "azure", "architecture"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合企业云架构、Azure 迁移和方案设计工作流。",
    examplePrompt: "调用 cloud-solution-architect，评审这个 Azure 部署拓扑。"
  },
  {
    id: "microsoft-frontend-design-review",
    name: "frontend-design-review",
    title: "Microsoft 前端设计审查",
    description: "Microsoft 官方前端设计审查 skill，用于检查 UI、可访问性和工程实现质量。",
    source: "https://github.com/microsoft/skills/tree/main/.github/skills/frontend-design-review",
    repository: "https://github.com/microsoft/skills",
    category: "前端审查",
    tags: ["microsoft", "frontend", "review"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合和 Anthropic/Vercel 前端 skill 搭配，形成设计-实现-审查闭环。",
    examplePrompt: "使用 frontend-design-review，审查这个表单页面的可访问性和布局。"
  },
  {
    id: "microsoft-github-issue-creator",
    name: "github-issue-creator",
    title: "GitHub Issue 创建",
    description: "Microsoft 官方 issue 创建 skill，用于把需求、问题和计划整理成 GitHub Issue。",
    source: "https://github.com/microsoft/skills/tree/main/.github/skills/github-issue-creator",
    repository: "https://github.com/microsoft/skills",
    category: "项目管理",
    tags: ["microsoft", "github", "issue"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合把 agent 产出的计划沉淀为可追踪任务。",
    examplePrompt: "调用 github-issue-creator，把这个实现计划拆成 GitHub Issues。"
  },
  {
    id: "apify-ultimate-scraper",
    name: "apify-ultimate-scraper",
    title: "Apify 通用抓取",
    description: "Apify 官方 agent skills 中的抓取 skill，用于网页数据采集与 scraper 设计。",
    source: "https://github.com/apify/agent-skills/tree/main/skills/apify-ultimate-scraper",
    repository: "https://github.com/apify/agent-skills",
    category: "网页数据",
    tags: ["apify", "scraping", "data"],
    agents: ["codex", "claude-code"],
    featuredReason: "Apify 官方技能集合，适合网页数据和自动化采集任务。",
    examplePrompt: "使用 apify-ultimate-scraper，帮我设计一个抓取产品价格的 Actor。"
  },
  {
    id: "apify-actor-development",
    name: "apify-actor-development",
    title: "Apify Actor 开发",
    description: "Apify 官方 Actor 开发 skill，用于创建和维护 Apify Actors。",
    source: "https://github.com/apify/agent-skills/tree/main/skills/apify-actor-development",
    repository: "https://github.com/apify/agent-skills",
    category: "网页数据",
    tags: ["apify", "actor", "automation"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合将网页自动化流程产品化为 Apify Actor。",
    examplePrompt: "调用 apify-actor-development，帮我创建一个抓取新闻列表的 Actor。"
  },
  {
    id: "apify-actorization",
    name: "apify-actorization",
    title: "Apify 代码 Actor 化",
    description: "将现有脚本、CLI 或项目包装成 Apify Actor，支持 JS/TS、Python 和通用命令行场景。",
    source: "https://github.com/apify/agent-skills/tree/main/skills/apify-actorization",
    repository: "https://github.com/apify/agent-skills",
    category: "网页数据",
    tags: ["apify", "actorization", "automation"],
    agents: ["codex", "claude-code"],
    featuredReason: "补齐从已有代码迁移到可运行 Actor 的工作流。",
    examplePrompt: "使用 apify-actorization，把这个 Python 抓取脚本包装成 Apify Actor。"
  },
  {
    id: "apify-generate-output-schema",
    name: "apify-generate-output-schema",
    title: "Apify 输出 Schema",
    description: "分析 Actor 源码并生成 dataset、output、key-value store 等输出 schema。",
    source: "https://github.com/apify/agent-skills/tree/main/skills/apify-generate-output-schema",
    repository: "https://github.com/apify/agent-skills",
    category: "网页数据",
    tags: ["apify", "schema", "actor"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合让采集结果更规范，便于下游应用消费。",
    examplePrompt: "调用 apify-generate-output-schema，为这个 Actor 生成 dataset_schema.json。"
  },
  {
    id: "apify-sdk-integration",
    name: "apify-sdk-integration",
    title: "Apify SDK 集成",
    description: "把 Apify 的抓取、自动化和数据提取能力接入现有 JS/TS 或 Python 应用。",
    source: "https://github.com/apify/agent-skills/tree/main/skills/apify-sdk-integration",
    repository: "https://github.com/apify/agent-skills",
    category: "网页数据",
    tags: ["apify", "sdk", "integration"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合把外部数据采集能力嵌入自己的产品或后端任务。",
    examplePrompt: "使用 apify-sdk-integration，把 Apify Actor 调用接入这个 Node.js 服务。"
  },
  {
    id: "anthropic-pdf",
    name: "pdf",
    title: "Anthropic PDF 文档处理",
    description: "Anthropic 官方 PDF skill，用于读取、拆分、合并、OCR、表单和水印等 PDF 任务。",
    source: "https://github.com/anthropics/skills/tree/main/skills/pdf",
    repository: "https://github.com/anthropics/skills",
    category: "文档处理",
    tags: ["anthropic", "pdf", "documents"],
    agents: ["codex", "claude-code"],
    featuredReason: "官方生产级文档 skill，适合把常见 PDF 工作流交给 agent 处理。",
    examplePrompt: "使用 pdf skill，提取这个 PDF 里的表格并整理成 Markdown。"
  },
  {
    id: "anthropic-docx",
    name: "docx",
    title: "Anthropic Word 文档处理",
    description: "Anthropic 官方 docx skill，用于创建、读取、编辑和格式化 Word 文档。",
    source: "https://github.com/anthropics/skills/tree/main/skills/docx",
    repository: "https://github.com/anthropics/skills",
    category: "文档处理",
    tags: ["anthropic", "docx", "word"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合报告、备忘录、模板和正式文档交付。",
    examplePrompt: "调用 docx，把这份会议纪要整理成带标题和目录的 Word 文档。"
  },
  {
    id: "anthropic-pptx",
    name: "pptx",
    title: "Anthropic 演示文稿处理",
    description: "Anthropic 官方 pptx skill，用于创建、读取、编辑和合并 PowerPoint 幻灯片。",
    source: "https://github.com/anthropics/skills/tree/main/skills/pptx",
    repository: "https://github.com/anthropics/skills",
    category: "文档处理",
    tags: ["anthropic", "pptx", "slides"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合把研究、方案和汇报内容转为可交付 slide deck。",
    examplePrompt: "使用 pptx skill，把这份方案摘要做成 8 页演示稿。"
  },
  {
    id: "anthropic-xlsx",
    name: "xlsx",
    title: "Anthropic 表格处理",
    description: "Anthropic 官方 xlsx skill，用于创建、读取、清洗、分析和格式化电子表格。",
    source: "https://github.com/anthropics/skills/tree/main/skills/xlsx",
    repository: "https://github.com/anthropics/skills",
    category: "文档处理",
    tags: ["anthropic", "xlsx", "spreadsheet"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合把 CSV、XLSX 和杂乱表格数据整理成可用工作簿。",
    examplePrompt: "调用 xlsx，清洗这个 CSV 并生成带筛选和汇总表的 Excel 文件。"
  },
  {
    id: "anthropic-skill-creator",
    name: "skill-creator",
    title: "Anthropic Skill 创建器",
    description: "Anthropic 官方 skill-creator，用于创建、修改、评估和优化 agent skills。",
    source: "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
    repository: "https://github.com/anthropics/skills",
    category: "Skill 开发",
    tags: ["anthropic", "skill", "authoring"],
    agents: ["codex", "claude-code"],
    featuredReason: "官方高星仓库里的创建指南，适合建立团队自己的 skill 生产流程。",
    examplePrompt: "使用 skill-creator，帮我把团队代码 review 流程沉淀成一个 SKILL.md。"
  },
  {
    id: "mattpocock-tdd",
    name: "tdd",
    title: "Matt Pocock TDD",
    description: "面向真实工程的红绿重构 skill，用测试先行方式开发功能或修复 bug。",
    source: "https://github.com/mattpocock/skills/tree/main/skills/engineering/tdd",
    repository: "https://github.com/mattpocock/skills",
    category: "工程工作流",
    tags: ["tdd", "testing", "engineering"],
    agents: ["codex", "claude-code"],
    featuredReason: "社区高星工程 skill 集合中的核心项，适合约束 coding agent 不盲写代码。",
    examplePrompt: "调用 tdd skill，先写失败测试，再修复这个边界条件 bug。"
  },
  {
    id: "mattpocock-diagnose",
    name: "diagnose",
    title: "Matt Pocock 诊断调试",
    description: "按复现、最小化、假设、插桩、修复、回归测试的顺序处理 bug 和性能问题。",
    source: "https://github.com/mattpocock/skills/tree/main/skills/engineering/diagnose",
    repository: "https://github.com/mattpocock/skills",
    category: "工程工作流",
    tags: ["debugging", "diagnosis", "engineering"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合把调试过程变得可验证，减少猜测式修复。",
    examplePrompt: "使用 diagnose，帮我定位这个接口偶发 500 的根因。"
  },
  {
    id: "mattpocock-improve-codebase-architecture",
    name: "improve-codebase-architecture",
    title: "代码库架构改进",
    description: "结合领域语言和 ADR 寻找模块深化、耦合收敛、可测试性和 agent 可导航性机会。",
    source: "https://github.com/mattpocock/skills/tree/main/skills/engineering/improve-codebase-architecture",
    repository: "https://github.com/mattpocock/skills",
    category: "工程工作流",
    tags: ["architecture", "refactor", "engineering"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合周期性审查 agent 参与开发后的复杂度积累。",
    examplePrompt: "调用 improve-codebase-architecture，审查这个模块有没有更深的边界。"
  },
  {
    id: "mattpocock-to-prd",
    name: "to-prd",
    title: "上下文转 PRD",
    description: "把当前对话上下文整理成 PRD，并可发布到项目 issue tracker。",
    source: "https://github.com/mattpocock/skills/tree/main/skills/engineering/to-prd",
    repository: "https://github.com/mattpocock/skills",
    category: "产品规划",
    tags: ["prd", "planning", "issues"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合把模糊需求沉淀成可评审、可拆解的产品文档。",
    examplePrompt: "使用 to-prd，把我们刚才讨论的 skill 管理功能整理成 PRD。"
  },
  {
    id: "mattpocock-to-issues",
    name: "to-issues",
    title: "计划拆成 Issues",
    description: "把计划、规格或 PRD 拆成独立可领取的垂直切片 issues。",
    source: "https://github.com/mattpocock/skills/tree/main/skills/engineering/to-issues",
    repository: "https://github.com/mattpocock/skills",
    category: "项目管理",
    tags: ["issues", "planning", "delivery"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合让多个 agent 或团队成员并行处理清晰任务。",
    examplePrompt: "调用 to-issues，把这个 PRD 拆成可以并行开发的 GitHub Issues。"
  },
  {
    id: "mattpocock-grill-me",
    name: "grill-me",
    title: "需求深问",
    description: "围绕计划或设计进行连续追问，直到关键分支和权衡被讲清楚。",
    source: "https://github.com/mattpocock/skills/tree/main/skills/productivity/grill-me",
    repository: "https://github.com/mattpocock/skills",
    category: "需求澄清",
    tags: ["planning", "questions", "alignment"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合在开发前减少误解，提升 agent 和用户的需求对齐。",
    examplePrompt: "使用 grill-me，围绕这个新功能方案连续追问我直到需求清楚。"
  },
  {
    id: "mattpocock-write-a-skill",
    name: "write-a-skill",
    title: "编写新 Skill",
    description: "创建结构正确、触发描述清晰、具备渐进披露资源的 agent skill。",
    source: "https://github.com/mattpocock/skills/tree/main/skills/productivity/write-a-skill",
    repository: "https://github.com/mattpocock/skills",
    category: "Skill 开发",
    tags: ["skill", "authoring", "workflow"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合让用户把经验、SOP 和领域流程快速变成可复用 skill。",
    examplePrompt: "调用 write-a-skill，把这份客户访谈 SOP 做成一个 agent skill。"
  },
  {
    id: "mattpocock-handoff",
    name: "handoff",
    title: "会话交接",
    description: "把当前对话压缩为交接文档，方便另一个 agent 或新会话继续。",
    source: "https://github.com/mattpocock/skills/tree/main/skills/productivity/handoff",
    repository: "https://github.com/mattpocock/skills",
    category: "效率工具",
    tags: ["handoff", "context", "agents"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合长任务、跨会话和多 agent 协作时保留上下文。",
    examplePrompt: "使用 handoff，把当前进展整理成下一位 agent 可继续执行的交接说明。"
  },
  {
    id: "mattpocock-git-guardrails-claude-code",
    name: "git-guardrails-claude-code",
    title: "Claude Code Git 防护",
    description: "为 Claude Code 设置 hooks，阻止 push、reset --hard、clean 等危险 Git 命令。",
    source: "https://github.com/mattpocock/skills/tree/main/skills/misc/git-guardrails-claude-code",
    repository: "https://github.com/mattpocock/skills",
    category: "安全防护",
    tags: ["git", "claude-code", "guardrails"],
    agents: ["claude-code"],
    featuredReason: "适合保护共享仓库，降低 agent 误执行破坏性 Git 操作的风险。",
    examplePrompt: "使用 git-guardrails-claude-code，为这个仓库配置 Claude Code Git 安全 hooks。"
  },
  {
    id: "microsoft-applicationinsights-web-ts",
    name: "applicationinsights-web-ts",
    title: "Application Insights Web TS",
    description: "为 Web 应用接入 Application Insights JavaScript SDK，覆盖 RUM、异常、依赖和前端 agent traces。",
    source: "https://github.com/microsoft/skills/tree/main/.github/skills/applicationinsights-web-ts",
    repository: "https://github.com/microsoft/skills",
    category: "微软生态",
    tags: ["microsoft", "application-insights", "typescript"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合生产 Web 应用观测和前后端 trace 关联。",
    examplePrompt: "调用 applicationinsights-web-ts，为这个 React 应用接入前端 RUM。"
  },
  {
    id: "microsoft-copilot-sdk",
    name: "copilot-sdk",
    title: "GitHub Copilot SDK",
    description: "指导使用 Copilot SDK 构建 Node.js、Python、Go 或 .NET 集成应用。",
    source: "https://github.com/microsoft/skills/tree/main/.github/skills/copilot-sdk",
    repository: "https://github.com/microsoft/skills",
    category: "微软生态",
    tags: ["microsoft", "copilot", "sdk"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合构建带自定义工具、MCP、会话和流式输出的 Copilot 应用。",
    examplePrompt: "使用 copilot-sdk，帮我设计一个带自定义工具的 Copilot SDK 服务。"
  },
  {
    id: "microsoft-entra-agent-id",
    name: "entra-agent-id",
    title: "Microsoft Entra Agent ID",
    description: "Microsoft Entra Agent ID 相关 skill，用于 agent 身份、安全和企业集成场景。",
    source: "https://github.com/microsoft/skills/tree/main/.github/skills/entra-agent-id",
    repository: "https://github.com/microsoft/skills",
    category: "身份与安全",
    tags: ["microsoft", "entra", "identity"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合企业 agent 身份、权限和合规设计。",
    examplePrompt: "调用 entra-agent-id，帮我规划企业 agent 的身份接入方案。"
  },
  {
    id: "microsoft-azure-storage-blob-rust",
    name: "azure-storage-blob-rust",
    title: "Azure Blob Rust SDK",
    description: "Azure Storage Blob Rust SDK skill，用于 Rust 项目中的 Blob 存储开发。",
    source: "https://github.com/microsoft/skills/tree/main/.github/skills/azure-storage-blob-rust",
    repository: "https://github.com/microsoft/skills",
    category: "微软生态",
    tags: ["microsoft", "azure", "rust"],
    agents: ["codex", "claude-code"],
    featuredReason: "适合 Azure SDK + Rust 项目中的文档驱动实现。",
    examplePrompt: "使用 azure-storage-blob-rust，帮我写一个上传文件到 Azure Blob 的 Rust 示例。"
  },
  ...HIGH_STAR_CATALOG_SKILLS
];
