import type { CatalogSkill } from "./types.js";

export const HIGH_STAR_CATALOG_SKILLS: CatalogSkill[] = [
  {
    id: "addyosmani-using-agent-skills",
    name: "using-agent-skills",
    title: "Using Agent Skills",
    description: "Meta-skill for discovering and applying the right skill during a task.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/using-agent-skills",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Skill Orchestration",
    tags: ["skills", "workflow", "routing"],
    agents: ["codex", "claude-code"],
    featuredReason: "From addyosmani/agent-skills, a high-star engineering workflow library; useful as the default router for larger skill sets.",
    examplePrompt: "Use using-agent-skills to choose the right workflow for this repository task."
  },
  {
    id: "addyosmani-api-and-interface-design",
    name: "api-and-interface-design",
    title: "API and Interface Design",
    description: "Guides stable public APIs, module boundaries, and frontend/backend contracts.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/api-and-interface-design",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Engineering Quality",
    tags: ["api", "contracts", "architecture"],
    agents: ["codex", "claude-code"],
    featuredReason: "Complements implementation skills with explicit interface and contract design discipline.",
    examplePrompt: "Use api-and-interface-design to design the boundary for this new settings API."
  },
  {
    id: "addyosmani-source-driven-development",
    name: "source-driven-development",
    title: "Source-Driven Development",
    description: "Grounds implementation decisions in official docs and cited sources.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/source-driven-development",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Engineering Quality",
    tags: ["docs", "sources", "correctness"],
    agents: ["codex", "claude-code"],
    featuredReason: "Good guardrail for framework and SDK work where outdated patterns are costly.",
    examplePrompt: "Use source-driven-development before changing this SDK integration."
  },
  {
    id: "addyosmani-incremental-implementation",
    name: "incremental-implementation",
    title: "Incremental Implementation",
    description: "Breaks multi-file implementation into verified, reviewable slices.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/incremental-implementation",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Engineering Quality",
    tags: ["delivery", "implementation", "testing"],
    agents: ["codex", "claude-code"],
    featuredReason: "Useful for keeping larger agent changes small, staged, and easier to review.",
    examplePrompt: "Use incremental-implementation to land this dashboard feature in small verified slices."
  },
  {
    id: "addyosmani-browser-testing-with-devtools",
    name: "browser-testing-with-devtools",
    title: "Browser Testing With DevTools",
    description: "Uses real browser data for DOM inspection, console errors, network analysis, and performance profiling.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/browser-testing-with-devtools",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Testing Verification",
    tags: ["browser", "devtools", "testing"],
    agents: ["codex", "claude-code"],
    featuredReason: "Adds runtime browser verification to UI and full-stack workflows.",
    examplePrompt: "Use browser-testing-with-devtools to inspect this local UI and report console or layout issues."
  },
  {
    id: "addyosmani-security-and-hardening",
    name: "security-and-hardening",
    title: "Security and Hardening",
    description: "Hardens code that handles untrusted input, authentication, storage, or external integrations.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/security-and-hardening",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Security",
    tags: ["security", "hardening", "review"],
    agents: ["codex", "claude-code"],
    featuredReason: "A high-signal security checklist for feature work before it reaches production.",
    examplePrompt: "Use security-and-hardening to review this login flow before shipping."
  },
  {
    id: "addyosmani-performance-optimization",
    name: "performance-optimization",
    title: "Performance Optimization",
    description: "Profiles and fixes performance bottlenecks, regressions, and Core Web Vitals issues.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/performance-optimization",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Performance",
    tags: ["performance", "profiling", "optimization"],
    agents: ["codex", "claude-code"],
    featuredReason: "Pairs well with browser and web-quality skills for measurable speed improvements.",
    examplePrompt: "Use performance-optimization to profile and reduce this page's slow interaction time."
  },
  {
    id: "addyosmani-observability-and-instrumentation",
    name: "observability-and-instrumentation",
    title: "Observability and Instrumentation",
    description: "Adds logging, metrics, tracing, and alerts so production behavior is diagnosable.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/observability-and-instrumentation",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Operations",
    tags: ["observability", "logging", "metrics"],
    agents: ["codex", "claude-code"],
    featuredReason: "Covers the post-merge visibility gap for production features and incident follow-up.",
    examplePrompt: "Use observability-and-instrumentation to add useful traces around this checkout path."
  },
  {
    id: "addyosmani-ci-cd-and-automation",
    name: "ci-cd-and-automation",
    title: "CI/CD and Automation",
    description: "Sets up quality gates, automated tests, and deployment pipeline changes.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/ci-cd-and-automation",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Operations",
    tags: ["ci", "cd", "automation"],
    agents: ["codex", "claude-code"],
    featuredReason: "Turns repo quality checks into repeatable automation instead of one-off manual steps.",
    examplePrompt: "Use ci-cd-and-automation to add a typecheck and test gate to this project."
  },
  {
    id: "addyosmani-documentation-and-adrs",
    name: "documentation-and-adrs",
    title: "Documentation and ADRs",
    description: "Records decisions, public API changes, and context future maintainers need.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/documentation-and-adrs",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Documentation",
    tags: ["docs", "adr", "decisions"],
    agents: ["codex", "claude-code"],
    featuredReason: "Keeps architectural and API changes understandable after the code diff ages.",
    examplePrompt: "Use documentation-and-adrs to write an ADR for this storage abstraction."
  },
  {
    id: "addyosmani-shipping-and-launch",
    name: "shipping-and-launch",
    title: "Shipping and Launch",
    description: "Prepares staged rollouts, production launch checks, monitoring, and rollback plans.",
    source: "https://github.com/addyosmani/agent-skills/tree/main/skills/shipping-and-launch",
    repository: "https://github.com/addyosmani/agent-skills",
    category: "Operations",
    tags: ["launch", "rollout", "rollback"],
    agents: ["codex", "claude-code"],
    featuredReason: "Useful for turning completed implementation into an actual deployable release plan.",
    examplePrompt: "Use shipping-and-launch to prepare a launch checklist for this feature."
  },
  {
    id: "github-premium-frontend-ui",
    name: "premium-frontend-ui",
    title: "Premium Frontend UI",
    description: "Crafts polished web experiences with motion, typography, and high-end UI composition.",
    source: "https://github.com/github/awesome-copilot/tree/main/skills/premium-frontend-ui",
    repository: "https://github.com/github/awesome-copilot",
    category: "Frontend Design",
    tags: ["frontend", "ui", "motion"],
    agents: ["codex", "claude-code"],
    featuredReason: "From GitHub's high-star awesome-copilot collection; complements existing frontend design skills with more premium UI craft.",
    examplePrompt: "Use premium-frontend-ui to redesign this landing page with stronger typography and motion."
  },
  {
    id: "github-gsap-framer-scroll-animation",
    name: "gsap-framer-scroll-animation",
    title: "GSAP and Framer Scroll Animation",
    description: "Builds scroll-triggered animations, parallax, pinned sections, and Framer Motion scroll effects.",
    source: "https://github.com/github/awesome-copilot/tree/main/skills/gsap-framer-scroll-animation",
    repository: "https://github.com/github/awesome-copilot",
    category: "Frontend Design",
    tags: ["frontend", "animation", "scroll"],
    agents: ["codex", "claude-code"],
    featuredReason: "A focused motion skill for the interaction details that general UI skills often leave underspecified.",
    examplePrompt: "Use gsap-framer-scroll-animation to add a tasteful scroll reveal to this product page."
  },
  {
    id: "github-chrome-devtools",
    name: "chrome-devtools",
    title: "Chrome DevTools",
    description: "Browser automation, debugging, screenshots, network analysis, and performance profiling with DevTools.",
    source: "https://github.com/github/awesome-copilot/tree/main/skills/chrome-devtools",
    repository: "https://github.com/github/awesome-copilot",
    category: "Testing Verification",
    tags: ["chrome", "devtools", "debugging"],
    agents: ["codex", "claude-code"],
    featuredReason: "A practical browser-debugging companion for local web app verification.",
    examplePrompt: "Use chrome-devtools to inspect this localhost page and identify runtime errors."
  },
  {
    id: "github-codeql",
    name: "codeql",
    title: "CodeQL",
    description: "Configures GitHub CodeQL code scanning, CLI analysis, SARIF output, and security workflows.",
    source: "https://github.com/github/awesome-copilot/tree/main/skills/codeql",
    repository: "https://github.com/github/awesome-copilot",
    category: "Security",
    tags: ["codeql", "security", "github-actions"],
    agents: ["codex", "claude-code"],
    featuredReason: "Adds a concrete static-analysis path for repositories that need security scanning.",
    examplePrompt: "Use codeql to add GitHub Actions code scanning for this TypeScript project."
  },
  {
    id: "github-agent-owasp-compliance",
    name: "agent-owasp-compliance",
    title: "Agent OWASP Compliance",
    description: "Checks AI agent codebases against OWASP Agentic Security Initiative risks.",
    source: "https://github.com/github/awesome-copilot/tree/main/skills/agent-owasp-compliance",
    repository: "https://github.com/github/awesome-copilot",
    category: "Security",
    tags: ["agent-security", "owasp", "audit"],
    agents: ["codex", "claude-code"],
    featuredReason: "Specialized for agent systems, where ordinary web security checklists miss agent-specific risk.",
    examplePrompt: "Use agent-owasp-compliance to audit this agent tool server before deployment."
  },
  {
    id: "github-agent-supply-chain",
    name: "agent-supply-chain",
    title: "Agent Supply Chain",
    description: "Verifies integrity manifests, plugin provenance, dependency pinning, and agent tool package tampering.",
    source: "https://github.com/github/awesome-copilot/tree/main/skills/agent-supply-chain",
    repository: "https://github.com/github/awesome-copilot",
    category: "Security",
    tags: ["supply-chain", "integrity", "plugins"],
    agents: ["codex", "claude-code"],
    featuredReason: "Useful when distributing skills, plugins, and agent tools across environments.",
    examplePrompt: "Use agent-supply-chain to generate an integrity manifest for these project skills."
  },
  {
    id: "github-agentic-eval",
    name: "agentic-eval",
    title: "Agentic Eval",
    description: "Designs evaluator, self-critique, rubric, and iterative improvement loops for agent outputs.",
    source: "https://github.com/github/awesome-copilot/tree/main/skills/agentic-eval",
    repository: "https://github.com/github/awesome-copilot",
    category: "Evaluation",
    tags: ["evals", "quality", "agents"],
    agents: ["codex", "claude-code"],
    featuredReason: "Adds an evaluation layer for quality-critical agent outputs and generated code.",
    examplePrompt: "Use agentic-eval to design a rubric for judging this agent's generated reports."
  },
  {
    id: "addyosmani-web-quality-audit",
    name: "web-quality-audit",
    title: "Web Quality Audit",
    description: "Audits performance, accessibility, SEO, and best practices with a Lighthouse-style workflow.",
    source: "https://github.com/addyosmani/web-quality-skills/tree/main/skills/web-quality-audit",
    repository: "https://github.com/addyosmani/web-quality-skills",
    category: "Web Quality",
    tags: ["lighthouse", "audit", "web-quality"],
    agents: ["codex", "claude-code"],
    featuredReason: "From addyosmani/web-quality-skills, a focused web-quality collection for measurable site improvements.",
    examplePrompt: "Use web-quality-audit to review this local site across performance, accessibility, SEO, and best practices."
  },
  {
    id: "addyosmani-core-web-vitals",
    name: "core-web-vitals",
    title: "Core Web Vitals",
    description: "Optimizes LCP, INP, and CLS for page experience and search ranking.",
    source: "https://github.com/addyosmani/web-quality-skills/tree/main/skills/core-web-vitals",
    repository: "https://github.com/addyosmani/web-quality-skills",
    category: "Web Quality",
    tags: ["core-web-vitals", "performance", "lighthouse"],
    agents: ["codex", "claude-code"],
    featuredReason: "Targets the web metrics that matter most for perceived speed and search visibility.",
    examplePrompt: "Use core-web-vitals to diagnose and improve LCP, INP, and CLS on this page."
  },
  {
    id: "addyosmani-accessibility",
    name: "accessibility",
    title: "Accessibility",
    description: "Audits and improves web accessibility with WCAG 2.2 guidance.",
    source: "https://github.com/addyosmani/web-quality-skills/tree/main/skills/accessibility",
    repository: "https://github.com/addyosmani/web-quality-skills",
    category: "Web Quality",
    tags: ["accessibility", "wcag", "a11y"],
    agents: ["codex", "claude-code"],
    featuredReason: "Adds a dedicated accessibility lane for keyboard, screen-reader, and WCAG work.",
    examplePrompt: "Use accessibility to audit this form for keyboard and screen-reader issues."
  },
  {
    id: "addyosmani-seo",
    name: "seo",
    title: "SEO",
    description: "Improves search visibility with metadata, structured data, sitemap, and SEO review patterns.",
    source: "https://github.com/addyosmani/web-quality-skills/tree/main/skills/seo",
    repository: "https://github.com/addyosmani/web-quality-skills",
    category: "Web Quality",
    tags: ["seo", "metadata", "structured-data"],
    agents: ["codex", "claude-code"],
    featuredReason: "Rounds out web-quality coverage beyond runtime performance and accessibility.",
    examplePrompt: "Use seo to review this product page's metadata and structured data."
  }
];
